# Generated by Django 4.2.10 on 2024-04-29 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoriaegzaminu', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Egzamin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('kategoria', models.CharField(max_length=45)),
                ('czas', models.CharField(max_length=45)),
                ('nazwa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projekt.kategoria')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
    ]
